export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAIL = "PRODUCT_FAIL";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const EDITE_SUCCESS = "EDITE_SUCCESS"